"""Check _eb_in_loop and else block processing"""
import sys, marshal, json
sys.path.insert(0, '.')
from core.cfg.cfg_builder import build_cfg
from core.cfg.region_analyzer import RegionAnalyzer
from core.cfg.region_ast_generator import RegionASTGenerator, BlockRole

pyc_path = '.trae/specs/decompiler-test-comprehensive-10rounds/rounds/round_02/test_engineer/minimal_repros/repro_r2_07_finally_implicit_return.pyc'
with open(pyc_path, 'rb') as f:
    f.read(16)
    code = marshal.load(f)

func_code = None
for c in code.co_consts:
    if hasattr(c, 'co_name') and c.co_name == 'test_finally_implicit_return':
        func_code = c
        break

cfg = build_cfg(func_code)
gen = RegionASTGenerator(cfg)
gen.regions = gen.region_analyzer.analyze()

try_region = None
for r in gen.regions:
    if hasattr(r, 'has_finally'):
        try_region = r
        break

# Check _eb_in_loop condition for else block 18
eb = try_region.else_blocks[0]
_parent_is_loop = isinstance(try_region.parent, __import__('core.cfg.region_analyzer', fromlist=['LoopRegion']).LoopRegion) or any(
    isinstance(r, __import__('core.cfg.region_analyzer', fromlist=['LoopRegion']).LoopRegion) and any(b in r.body_blocks for b in try_region.try_blocks)
    for r in gen.regions
)
print(f"_parent_is_loop: {_parent_is_loop}")
print(f"try_region.parent: {type(try_region.parent).__name__ if try_region.parent else None}")

# Check if any try_block is in a LoopRegion.body_blocks
from core.cfg.region_analyzer import LoopRegion
for r in gen.regions:
    if isinstance(r, LoopRegion):
        print(f"LoopRegion entry={r.entry.start_offset}, body_blocks={[b.start_offset for b in r.body_blocks]}")
        for tb in try_region.try_blocks:
            if tb in r.body_blocks:
                print(f"  try_block {tb.start_offset} in LoopRegion body_blocks!")

# Check the else block role
role = gen.region_analyzer.get_block_role(eb)
print(f"\neb role: {role}")
print(f"eb.start_offset: {eb.start_offset}")

# Check if _generate_block_statements returns Return
ebs = gen._generate_block_statements(eb)
print(f"ebs: {json.dumps(ebs, default=str)}")

# Now my fix checks type == 'Expr', but it's 'Return'
# So the fix doesn't trigger, and ebs = [Return(results)] is added to orelse_stmts
# via the L17820 path: if ebs: orelse_stmts.extend(ebs)
# But then orelse_stmts should have [Return(results)]!
# Let me check if orelse_stmts gets set correctly
print(f"\nBut wait - my fix checks _ret_ebs[0].get('type') == 'Expr'")
print(f"Actual type: {ebs[0].get('type') if ebs else 'N/A'}")
print(f"So the fix condition doesn't match, and code falls through to L17836")
print(f"At L17836: ebs = self._generate_block_statements(eb) again?")
print(f"No - L17836 is AFTER the fix block. The fix block has 'continue' at L17835")
print(f"If fix doesn't trigger, code falls to L17836: ebs = self._generate_block_statements(eb)")
print(f"But block 18 was NOT marked generated by the fix, so this should work")
