#!/usr/bin/env python3
"""R93 check: does the decompiled source have an explicit 'return None' at the
end of the then branch of 'if count_min == 0:'?"""
import sys
sys.path.insert(0, '.')
from pycdc import decompile_pyc

target_pyc = "site-packages/IQCommon/api/klinedata.pyc"
decomp_src = decompile_pyc(target_pyc)

lines = decomp_src.split('\n')
in_func = False
func_lines = []
for i, line in enumerate(lines):
    if 'def get_multiminute_his_data' in line:
        in_func = True
    if in_func:
        func_lines.append((i+1, line))
        if len(func_lines) > 70:
            break

for lineno, line in func_lines:
    # Highlight the area around 'if count_min == 0:'
    if 494 <= lineno <= 500:
        print(f">>> {lineno:4d}: {line}")
    elif 'return' in line.lower():
        print(f"  {lineno:4d}: {line}")

# Also check: the decompiled bytecode has LOAD_CONST None + RETURN_VALUE at offset 820
# This is generated by the Python compiler when:
# 1. The then branch of 'if count_min == 0:' ends with a 'return None' statement
# 2. OR the then branch is the last code in the function (implicit return)
# 
# Since the decompiled source doesn't have 'return None' explicitly,
# the compiler must be generating it implicitly.
# This happens when the Python compiler sees that the then branch
# ends without a return statement, and the function has no more code after the if.
# But the function DOES have code after the if (the else branch and return).
#
# The issue must be that the decompiled source has a different structure
# where the else branch is placed at a different scope level.

# Let me check the exact indentation of the else branch
print("\n--- Indentation check ---")
for lineno, line in func_lines:
    if 'else' in line and 494 <= lineno <= 550:
        indent = len(line) - len(line.lstrip())
        print(f"  {lineno:4d}: indent={indent} {line}")
