#!/usr/bin/env python3
"""R93 check: is the LOAD_CONST None + RETURN_VALUE at offset 820-822 
generated by the decompiler or by the Python compiler?"""
import sys, dis, types, marshal
sys.path.insert(0, '.')
from pycdc import decompile_pyc

target_pyc = "site-packages/IQCommon/api/klinedata.pyc"
decomp_src = decompile_pyc(target_pyc)
decomp_code = compile(decomp_src, '<decompiled>', 'exec')

def find_function(code, name):
    for const in code.co_consts:
        if isinstance(const, types.CodeType):
            if const.co_name == name:
                return const
            inner = find_function(const, name)
            if inner:
                return inner
    return None

decomp_func = find_function(decomp_code, 'get_multiminute_his_data')

print("Decompiled bytecode around offset 810-830:")
for instr in dis.get_instructions(decomp_func):
    if 810 <= instr.offset <= 830:
        print(f"  {instr.offset:4d} {instr.opname:30s} {instr.argrepr}")

# Check the source lines around offset 820
# The LOAD_CONST None at 820 is likely from the Python compiler adding 
# implicit return None at the end of a branch.
# Let's check what source code structure produces this.

# Also check: what's at offset 824 in the original?
with open(target_pyc, 'rb') as f:
    f.read(16)
    orig_code = marshal.loads(f.read())
orig_func = find_function(orig_code, 'get_multiminute_his_data')

print("\nOriginal bytecode around offset 810-830:")
for instr in dis.get_instructions(orig_func):
    if 810 <= instr.offset <= 830:
        print(f"  {instr.offset:4d} {instr.opname:30s} {instr.argrepr}")

# Now check: what source line does offset 820 correspond to?
# In the decompiled source, the 'return his_data_dict' at line 497 generates
# LOAD_FAST his_data_dict + RETURN_VALUE at offset 816-818.
# After that, the Python compiler should generate JUMP_FORWARD to skip the else.
# But instead it generates LOAD_CONST None + RETURN_VALUE.

# Let me check if there's a 'return None' in the decompiled source
# at the end of the if-then branch
print("\nSearching for 'return None' in decompiled source:")
lines = decomp_src.split('\n')
for i, line in enumerate(lines):
    if 'return None' in line and 485 <= i+1 <= 550:
        print(f"  {i+1:4d}: {line}")

# The key question: does the decompiled source have any code that would
# cause the compiler to generate LOAD_CONST None + RETURN_VALUE at offset 820?
# Let me check the AST structure around offset 820
