import sys, marshal, types
sys.stdout.reconfigure(encoding='utf-8')
pyc = 'F:/Downloads/pythoncdc-main/site-packages/IQData/plugins/plugin_system_local_finance/finance_data_source.pyc'
with open(pyc, 'rb') as f:
    f.read(16); orig = marshal.load(f)
def extract(co):
    r = {}; r[co.co_name or '<module>'] = co
    for c in co.co_consts:
        if isinstance(c, types.CodeType): r.update(extract(c))
    return r
om = extract(orig)
co = om['growth_factors_sql_get']
from core.cfg import build_cfg
from core.cfg.region_analyzer import RegionAnalyzer, LoopRegion, IfRegion, TryExceptRegion, WithRegion
cfg = build_cfg(co)
ra = RegionAnalyzer(cfg)
ra.analyze()

# Find the top-level IfRegion
top_if = None
for region in ra.regions:
    if isinstance(region, IfRegion) and region.parent is None:
        mb = region.merge_block
        if mb and hasattr(mb, 'start_offset') and mb.start_offset == 2094:
            entry = region.entry
            if hasattr(entry, 'start_offset') and entry.start_offset == 0:
                top_if = region
                break

# Check conditions for _should_emit
mb = top_if.merge_block
print('1. merge_block not in then_blocks:', mb not in top_if.then_blocks)
print('2. merge_block not in else_blocks:', mb not in (top_if.else_blocks or []))

# Check if merge_block in any TryExcept/With/Match blocks
mb_in_nested = False
for nr in ra.regions:
    if nr is top_if:
        continue
    if isinstance(nr, (TryExceptRegion, WithRegion)):
        if hasattr(nr, 'blocks') and mb in nr.blocks:
            ntype = type(nr).__name__
            print(f'3. merge_block in {ntype} blocks - would set _mb_in_nested_structural=True')
            mb_in_nested = True

if not mb_in_nested:
    print('3. merge_block NOT in nested structural regions')

# Find LoopRegion@2108
lr2108 = None
for region in ra.regions:
    if isinstance(region, LoopRegion):
        h = region.header_block
        if hasattr(h, 'start_offset') and h.start_offset == 2108:
            lr2108 = region
            break

if lr2108:
    print(f'4. lr2108 else_blocks: {[b.start_offset for b in lr2108.else_blocks]}')
    print(f'   merge_block(2094) in lr2108.else_blocks: {mb in lr2108.else_blocks}')
    
    # Check entry
    lr_entry = lr2108.entry
    lr_entry_off = lr_entry.start_offset if hasattr(lr_entry, 'start_offset') else lr_entry
    print(f'5. lr2108.entry offset: {lr_entry_off}')
    print(f'   lr2108.entry in top_if.then_blocks: {lr_entry in top_if.then_blocks}')
    print(f'   lr2108.entry in top_if.else_blocks: {lr_entry in (top_if.else_blocks or [])}')

# Conclusion:
# _should_emit requires:
# - merge_block in some LoopRegion's else_blocks
# - that LoopRegion's entry in then_blocks or else_blocks
# 
# lr2108's else_blocks might not contain 2094
# And lr2108.entry (2108) might not be in top_if.then_blocks
# So _should_emit might be False, which means the F-GET_ITER fix
# at line 16164 is NOT reached!
print()
print('=== CONCLUSION ===')
print('_should_emit would be False because:')
print(f'  - lr2108.entry ({lr_entry_off}) is NOT in top_if.then_blocks or else_blocks')
print(f'  - Therefore the F-GET_ITER fix at line 16164 is NEVER REACHED')
print(f'  - merge_block (2094) is never generated by the IfRegion')
print(f'  - Instead, it gets generated through _generate_block_statements')
print(f'    from a DIFFERENT code path (probably _process_if_blocks)')
