"""Resident guard: the in-place products must match what the CURRENT code emits.

Why this exists: after reverting a candidate this session, `core/` matched its sealed hashes but
`site-packages/**OK.py` still held products generated by the reverted code — a tree whose products no
longer come from its code makes every later `pyc_verify single` (which is compare-only, never regen)
read a state that no code can produce. The gate's regen stage fixes it, but only when someone runs it.

Cheap by design: four small corpus files, decompiled into $TEMP, byte-compared against the in-place
products. Any mismatch names the file and how it differs; nothing is ever written to site-packages.
"""
import os
import subprocess
import sys
import tempfile
import unittest

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SAMPLES = [
    "IQEngine/core/strategy/strategy_universe.pyc",
    "fly/dumpload/load_daily.pyc",
    "IQEngine/plugins/plugin_system_matcher/matcher.pyc",
    "IQCommon/util/trade_info_utils.pyc",
]


class TestProductFreshness(unittest.TestCase):
    def test_products_match_current_code(self):
        out_dir = tempfile.mkdtemp(prefix="freshness_")
        stale = []
        for rel in SAMPLES:
            pyc = os.path.join(ROOT, "site-packages", rel)
            prod = pyc[:-4] + "OK.py"
            if not (os.path.exists(pyc) and os.path.exists(prod)):
                continue                      # corpus not provisioned here: nothing to certify
            mine = os.path.join(out_dir, os.path.basename(prod))
            r = subprocess.run([sys.executable, "-X", "utf8", "pycdc.py", "--region", pyc, "-o", mine],
                               cwd=ROOT, capture_output=True, timeout=240)
            if r.returncode != 0 or not os.path.exists(mine) or os.path.getsize(mine) == 0:
                stale.append("%s: producer failed rc=%d size=%s" % (
                    rel, r.returncode, os.path.getsize(mine) if os.path.exists(mine) else "missing"))
                continue
            a = open(prod, "rb").read()
            b = open(mine, "rb").read()
            if a != b:
                la, lb = a.decode("utf-8", "replace").splitlines(), b.decode("utf-8", "replace").splitlines()
                diff = sum(1 for x, y in zip(la, lb) if x != y) + abs(len(la) - len(lb))
                stale.append("%s: in-place product differs from current code (%d lines, %d/%d bytes)"
                             % (rel, diff, len(a), len(b)))
        self.assertEqual([], stale,
                         "stale products: site-packages products were not produced by the current "
                         "code — run the gate regen stage (gate_chain.py / gate_round.py --stage regen)")


if __name__ == "__main__":
    unittest.main()
