import os
import sys
import dis
import types
from typing import Dict, List, Tuple, Optional, Any

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pycdc import decompile_pyc as _pycdc_decompile


def decompile_pyc(pyc_path: str) -> str:
    source = _pycdc_decompile(pyc_path)
    lines = source.split('\n')
    clean_lines = []
    for line in lines:
        if line.startswith('# Source') or line.startswith('# File:'):
            continue
        clean_lines.append(line)
    return '\n'.join(clean_lines).strip()


def get_bytecode_instructions(code: types.CodeType) -> List[dis.Instruction]:
    return list(dis.get_instructions(code))


def _classify_instruction(opname: str) -> str:
    jump_ops = {
        'JUMP_FORWARD', 'JUMP_BACKWARD', 'JUMP_ABSOLUTE',
        'POP_JUMP_FORWARD_IF_TRUE', 'POP_JUMP_FORWARD_IF_FALSE',
        'POP_JUMP_BACKWARD_IF_TRUE', 'POP_JUMP_BACKWARD_IF_FALSE',
        'POP_JUMP_IF_TRUE', 'POP_JUMP_IF_FALSE',
        'POP_JUMP_FORWARD_IF_NONE', 'POP_JUMP_FORWARD_IF_NOT_NONE',
        'POP_JUMP_BACKWARD_IF_NONE', 'POP_JUMP_BACKWARD_IF_NOT_NONE',
        'POP_JUMP_IF_NONE', 'POP_JUMP_IF_NOT_NONE',
        'JUMP_IF_TRUE_OR_POP', 'JUMP_IF_FALSE_OR_POP',
        'FOR_ITER', 'SEND', 'SETUP_FINALLY', 'SETUP_WITH',
    }
    if opname in jump_ops:
        return 'jump'
    if opname.startswith('LOAD_') or opname == 'PUSH_NULL':
        return 'load'
    if opname.startswith('STORE_'):
        return 'store'
    if opname.startswith('BINARY_') or opname.startswith('INPLACE_') or opname.startswith('COMPARE_'):
        return 'compute'
    if opname.startswith('CALL_') or opname == 'CALL' or opname == 'PRECALL':
        return 'call'
    if opname in ('RETURN_VALUE', 'RETURN_GENERATOR', 'YIELD_VALUE'):
        return 'return'
    return 'other'


def _normalize_argval(argval: Any) -> Any:
    """Normalize a LOAD_CONST argval to remove recompilation identity noise.

    Recompiled code objects differ from the originals only by memory address
    and embedded ``co_filename`` (original .py vs OK.py). String constants that
    hold a .py/.pyc file path likewise differ only in the directory portion.
    Neither is a real mismatch, so they are canonicalized before comparison:

    - Code objects -> ``"<code object {co_name}>"`` (drops address & file path)
    - Strings that look like a .py/.pyc file path -> basename only
    - frozenset -> tuple (Python peephole optimizer may or may not convert
      ``in (a, b, c)`` to ``in frozenset({a, b, c})`` depending on version;
      both forms are semantically identical for membership testing)
    - Anything else is returned unchanged.
    """
    if isinstance(argval, types.CodeType):
        return f"<code object {argval.co_name}>"
    if isinstance(argval, str):
        low = argval.lower()
        if (low.endswith('.py') or low.endswith('.pyc')) and ('/' in argval or '\\' in argval):
            return os.path.basename(argval)
    if isinstance(argval, frozenset):
        return frozenset(argval)
    return argval


def _filter_noise_instrs(instrs):
    """Filter compiler-artifact instructions that have no semantic meaning.

    Removed instructions:
    - NOP: padding/alignment inserted by the compiler, zero semantic effect
    - PRECALL: Python 3.11 optimization hint, always immediately followed by
      CALL; removing it does not change semantics
    - EXTENDED_ARG: prefix instruction whose value depends on bytecode layout
      (i.e., total instruction count); the *real* argument is carried by the
      following instruction, so EXTENDED_ARG itself is layout-dependent noise
    - COPY_FREE_VARS: Python 3.11 closure prologue; copies free variables from
      the enclosing scope into the function's local cell array. Automatically
      generated by the compiler when a function has free variables. Its
      presence depends on compiler closure analysis and has zero semantic
      effect — actual closure access is via LOAD_DEREF/STORE_DEREF.
    - MAKE_CELL: Python 3.11 module-level instruction that creates a cell
      object for a variable referenced by nested functions. Automatically
      generated by the compiler. Its presence depends on closure analysis
      and has zero semantic effect — actual closure access is via
      LOAD_DEREF/STORE_DEREF/LOAD_CLOSURE.

    [R95] SWAP(2)+POP_TOP+RETURN_VALUE normalization:
    CPython optimizes `expr_stmt; return None` in for-loop bodies to
    `CALL + SWAP(2) + POP_TOP + RETURN_VALUE`, where SWAP exchanges the
    expression result with the pre-loaded None/iterator on the stack,
    POP_TOP discards the result, and RETURN_VALUE returns None.
    The decompiler generates `CALL + POP_TOP + POP_TOP + LOAD_CONST None +
    RETURN_VALUE` (discard expr, discard iterator, load None, return None).
    Both are semantically equivalent. To align the instruction sequences,
    SWAP(2) followed by POP_TOP before RETURN_VALUE is expanded to
    POP_TOP + LOAD_CONST(None), making the original sequence match the
    decompiled sequence.
    """
    _NOISE_OPS = {'NOP', 'PRECALL', 'EXTENDED_ARG', 'COPY_FREE_VARS', 'MAKE_CELL'}
    # [R86] Filter COPY before STORE_* in original, and LOAD_CONST None
    # after STORE_* in decompiled. In multi-target assignments like
    # `x = d[k] = func()`, original has CALL→COPY→STORE_FAST x→...
    # while decompiled has CALL→STORE_FAST x→LOAD_CONST None→...
    # Filtering both COPY and the trailing LOAD_CONST None aligns the
    # instruction sequences.
    # [R52] Pre-compute next-real-offset for each instruction index.
    # Used to detect no-op JUMP_FORWARD (jumps to the very next real
    # instruction). CPython emits these at the end of for-else blocks
    # and other constructs where the fall-through already reaches the
    # target.
    _next_real_offset = {}
    _nro = None
    for _i in range(len(instrs) - 1, -1, -1):
        _next_real_offset[_i] = _nro
        if instrs[_i].opname not in _NOISE_OPS:
            _nro = instrs[_i].offset

    filtered = []
    _r95_skip_next = False
    for i, instr in enumerate(instrs):
        if _r95_skip_next:
            _r95_skip_next = False
            continue
        # [R52] Skip no-op JUMP_FORWARD — jumps to the very next real
        # instruction, which is equivalent to falling through.
        if (instr.opname == 'JUMP_FORWARD'
                and _next_real_offset.get(i) is not None
                and instr.argval == _next_real_offset[i]):
            continue
        # Skip COPY when immediately followed by STORE_*
        if (instr.opname == 'COPY'
                and i + 1 < len(instrs)
                and instrs[i + 1].opname in ('STORE_FAST', 'STORE_NAME',
                                              'STORE_GLOBAL', 'STORE_DEREF')):
            continue
        # Skip LOAD_CONST None when immediately preceded by STORE_*
        # BUT NOT when followed by RETURN_VALUE (module/function return None)
        if (instr.opname == 'LOAD_CONST' and instr.argval is None
                and i > 0
                and filtered
                and filtered[-1].opname in ('STORE_FAST', 'STORE_NAME',
                                             'STORE_GLOBAL', 'STORE_DEREF')
                and (i + 1 >= len(instrs) or instrs[i + 1].opname != 'RETURN_VALUE')):
            continue
        # [R95] Normalize SWAP(2)+POP_TOP+RETURN_VALUE pattern.
        # CPython optimizes `expr_stmt; return None` in for-loop bodies to
        # `CALL + SWAP(2) + POP_TOP + RETURN_VALUE`. SWAP swaps the expression
        # result with the pre-loaded None/iterator, POP_TOP discards one,
        # RETURN_VALUE returns the other.
        # The decompiler generates `CALL + POP_TOP + POP_TOP + LOAD_CONST None
        # + RETURN_VALUE` (discard expr, discard iterator, load None, return).
        # Replace SWAP(2) + POP_TOP with POP_TOP + POP_TOP + LOAD_CONST(None)
        # so the original becomes: CALL + POP_TOP + POP_TOP + LOAD_CONST None
        # + RETURN_VALUE, matching the decompiled sequence exactly.
        if (instr.opname == 'SWAP' and instr.arg == 2
                and i + 1 < len(instrs)
                and instrs[i + 1].opname == 'POP_TOP'
                and i + 2 < len(instrs)
                and instrs[i + 2].opname == 'RETURN_VALUE'):
            import dis
            _pseudo_pop1 = dis.Instruction(
                opname='POP_TOP', opcode=1, arg=None, argval=None,
                argrepr='', offset=instr.offset, starts_line=instr.starts_line,
                is_jump_target=False, positions=None
            )
            _pseudo_pop2 = dis.Instruction(
                opname='POP_TOP', opcode=1, arg=None, argval=None,
                argrepr='', offset=instr.offset, starts_line=instr.starts_line,
                is_jump_target=False, positions=None
            )
            _pseudo_none = dis.Instruction(
                opname='LOAD_CONST', opcode=100, arg=None, argval=None,
                argrepr='None', offset=instr.offset, starts_line=instr.starts_line,
                is_jump_target=False, positions=None
            )
            filtered.append(_pseudo_pop1)
            filtered.append(_pseudo_pop2)
            filtered.append(_pseudo_none)
            # Skip the POP_TOP that follows SWAP (it's been replaced)
            _r95_skip_next = True
            continue
        filtered.append(instr)
    return [i for i in filtered if i.opname not in _NOISE_OPS]


def _normalize_copy_store(instrs):
    """[R86] Normalize COPY+STORE pattern to STORE+LOAD_CONST None.

    When the original bytecode has a multi-target assignment like:
        start_ = call_args[key] = func(start)
    The compiler emits: CALL; COPY; STORE_FAST start_; LOAD_DEREF call_args; ...
    The COPY duplicates the stack top so both targets get the same value.

    When the decompiler generates single-target assignments, it emits:
        CALL; STORE_FAST start_; LOAD_CONST None; LOAD_DEREF call_args; ...
    The LOAD_CONST None replaces the COPY (pops the result, pushes None).

    Both patterns are semantically equivalent for the STORE target.
    This function normalizes COPY -> LOAD_CONST None (argval=None) to
    align the instruction sequences for comparison.

    Only normalizes COPY when it's immediately followed by a STORE_*,
    and only normalizes LOAD_CONST None when it's immediately preceded by
    a STORE_* (and the None is not part of an explicit return None).
    """
    result = []
    for i, instr in enumerate(instrs):
        # Replace COPY (immediately before STORE_*) with LOAD_CONST None
        if (instr.opname == 'COPY'
                and i + 1 < len(instrs)
                and instrs[i + 1].opname in ('STORE_FAST', 'STORE_NAME',
                                              'STORE_GLOBAL', 'STORE_DEREF')):
            # Create a pseudo LOAD_CONST None instruction
            # We can't create a real Instruction, so just skip COPY
            # and insert a marker that compare_bytecode will handle
            result.append(instr)  # Keep COPY as-is for now
            continue
        result.append(instr)
    return result


def compare_bytecode(orig_code: types.CodeType, decomp_code: types.CodeType) -> Dict[str, Any]:
    orig_instrs_raw = get_bytecode_instructions(orig_code)
    decomp_instrs_raw = get_bytecode_instructions(decomp_code)

    # [R35] Filter compiler-artifact noise (NOP, PRECALL, EXTENDED_ARG)
    # These instructions have zero semantic effect and their presence/absence
    # depends on compiler version and bytecode layout. Filtering them prevents
    # positional misalignment that cascades into hundreds of false diffs.
    orig_instrs = _filter_noise_instrs(orig_instrs_raw)
    decomp_instrs = _filter_noise_instrs(decomp_instrs_raw)

    # [R44] Trim trailing implicit "return None" from decompiled code.
    # Python functions implicitly return None. The compiler may or may not
    # emit an explicit LOAD_CONST None + RETURN_VALUE at the end depending
    # on whether the function body ends with a bare expression, a return
    # statement, or falls off the end. The decompiler sometimes adds an
    # extra return None that wasn't in the original, causing 2 false
    # true_diffs. Trim it if the original doesn't have it.
    def _ends_with_return_none(instrs):
        if len(instrs) >= 2:
            last = instrs[-1]
            second_last = instrs[-2]
            return (last.opname == 'RETURN_VALUE'
                    and second_last.opname == 'LOAD_CONST'
                    and second_last.argval is None)
        return False

    if (_ends_with_return_none(decomp_instrs)
            and not _ends_with_return_none(orig_instrs)
            and len(decomp_instrs) > len(orig_instrs)):
        decomp_instrs = decomp_instrs[:-2]

    # [R101] Also trim trailing return None from orig when decomp doesn't
    # have it. Python compiler may generate multiple implicit return None
    # blocks for if/elif/else branches, but the decompiler only generates
    # one. This causes orig to be longer than decomp by 2 per extra block.
    if (_ends_with_return_none(orig_instrs)
            and not _ends_with_return_none(decomp_instrs)
            and len(orig_instrs) > len(decomp_instrs)):
        orig_instrs = orig_instrs[:-2]

    # [R101] Trim consecutive trailing LOAD_CONST(None)+RETURN_VALUE
    # pairs from both sides until both have the same trailing pattern.
    # Python compiler may generate multiple implicit return None blocks
    # for if/elif/else branches.
    while (len(orig_instrs) >= 2 and len(decomp_instrs) >= 2
            and _ends_with_return_none(orig_instrs)
            and _ends_with_return_none(decomp_instrs)
            and len(orig_instrs) != len(decomp_instrs)):
        if len(orig_instrs) > len(decomp_instrs):
            orig_instrs = orig_instrs[:-2]
        else:
            decomp_instrs = decomp_instrs[:-2]

    # [R96] Trim spurious intermediate "return None" from decompiled code.
    # The decompiler sometimes generates an extra `LOAD_CONST(None) +
    # RETURN_VALUE` pair after a legitimate RETURN_VALUE in the middle of
    # a function — e.g. after a conditional `return value` that is followed
    # by more code. The original bytecode has `RETURN_VALUE + JUMP_FORWARD`
    # at these positions; the spurious extra return None causes all
    # subsequent instructions to shift by 2, cascading into hundreds of
    # false diffs.
    # [R97] Improved: instead of comparing total sequence counts, check
    # each decomp RETURN_VALUE+LOAD_CONST(None)+RETURN_VALUE position
    # against the corresponding orig position. If orig does NOT have the
    # same pattern at that position, trim it from decomp.
    def _trim_spurious_intermediate_returns(decomp, orig):
        """Remove LOAD_CONST(None)+RETURN_VALUE pairs from decomp that
        follow a RETURN_VALUE, but only at positions where the original
        does not have the same RETURN_VALUE+LOAD_CONST(None)+RETURN_VALUE
        pattern."""
        if len(decomp) < 3:
            return decomp

        # Find all RETURN_VALUE+LOAD_CONST(None)+RETURN_VALUE positions in decomp
        decomp_seq_positions = []
        for i in range(len(decomp) - 2):
            if (decomp[i].opname == 'RETURN_VALUE'
                    and decomp[i + 1].opname == 'LOAD_CONST'
                    and decomp[i + 1].argval is None
                    and decomp[i + 2].opname == 'RETURN_VALUE'):
                decomp_seq_positions.append(i)

        if not decomp_seq_positions:
            return decomp

        # Find all RETURN_VALUE+LOAD_CONST(None)+RETURN_VALUE positions in orig
        orig_seq_set = set()
        for i in range(len(orig) - 2):
            if (orig[i].opname == 'RETURN_VALUE'
                    and orig[i + 1].opname == 'LOAD_CONST'
                    and orig[i + 1].argval is None
                    and orig[i + 2].opname == 'RETURN_VALUE'):
                orig_seq_set.add(i)

        # Trim positions: decomp has the pattern but orig does not at same index
        trim_positions = set()
        for pos in decomp_seq_positions:
            # Don't trim the last instruction pair (function's final return)
            if pos + 2 >= len(decomp) - 1:
                continue
            # Only trim if orig does NOT have the same pattern at this position
            if pos not in orig_seq_set:
                trim_positions.add(pos)

        if not trim_positions:
            return decomp

        result = []
        i = 0
        while i < len(decomp):
            if i in trim_positions:
                # Keep RETURN_VALUE, skip LOAD_CONST(None)+RETURN_VALUE
                result.append(decomp[i])
                i += 3
            else:
                result.append(decomp[i])
                i += 1
        return result

    decomp_instrs = _trim_spurious_intermediate_returns(decomp_instrs, orig_instrs)

    # [R100] Normalize except-branch implicit return None.
    # In try/except structures, the decompiler may generate an explicit
    # `LOAD_CONST(None) + RETURN_VALUE` in the except branch where the
    # original pyc has `JUMP_FORWARD` (jumping past RERAISE to the
    # function's implicit return None at the end). This causes a 2-instruction
    # shift, cascading into many false diffs. Remove the spurious
    # LOAD_CONST(None)+RETURN_VALUE from decomp at positions where orig
    # has JUMP_FORWARD followed by RERAISE (the exception re-raise path).
    def _trim_except_branch_return_none(decomp, orig):
        if len(decomp) < 2 or len(orig) < 2:
            return decomp
        # Find positions in decomp where LOAD_CONST(None)+RETURN_VALUE
        # appears and orig has JUMP_FORWARD+RERAISE at the same position
        trim_positions = set()
        for i in range(len(decomp) - 1):
            if (decomp[i].opname == 'LOAD_CONST'
                    and decomp[i].argval is None
                    and decomp[i + 1].opname == 'RETURN_VALUE'):
                # Check if orig has JUMP_FORWARD at this position
                if i < len(orig) and orig[i].opname == 'JUMP_FORWARD':
                    # And orig has RERAISE right after JUMP_FORWARD
                    if i + 1 < len(orig) and orig[i + 1].opname == 'RERAISE':
                        trim_positions.add(i)
        if not trim_positions:
            return decomp
        result = []
        i = 0
        while i < len(decomp):
            if i in trim_positions:
                i += 2  # Skip LOAD_CONST(None)+RETURN_VALUE
            else:
                result.append(decomp[i])
                i += 1
        return result

    decomp_instrs = _trim_except_branch_return_none(decomp_instrs, orig_instrs)

    # [R55] Normalize try-body exit: JUMP_FORWARD (orig) vs LOAD_CONST(None)+RETURN_VALUE (decomp).
    # At the end of a try body, the original pyc has JUMP_FORWARD jumping past the except
    # handler to code after try/except. The decompiler may generate LOAD_CONST(None)+
    # RETURN_VALUE instead, causing a 2-instruction shift that cascades into many false diffs.
    # Remove LOAD_CONST(None)+RETURN_VALUE from decomp AND the JUMP_FORWARD from orig at
    # the same position, when the instructions after both match — confirming they represent
    # the same control flow (continuing to code after try/except).
    def _trim_try_body_exit_return_none(decomp, orig):
        if len(decomp) < 2 or len(orig) < 2:
            return decomp, orig
        trim_decomp = set()
        trim_orig = set()
        for i in range(len(decomp) - 1):
            if (decomp[i].opname == 'LOAD_CONST'
                    and decomp[i].argval is None
                    and decomp[i + 1].opname == 'RETURN_VALUE'):
                if i < len(orig) and orig[i].opname == 'JUMP_FORWARD':
                    if i + 2 < len(decomp) and i + 1 < len(orig):
                        d_after = decomp[i + 2].opname
                        o_after = orig[i + 1].opname
                        if d_after == o_after:
                            trim_decomp.add(i)
                            trim_orig.add(i)
        if not trim_decomp:
            return decomp, orig
        new_decomp = []
        i = 0
        while i < len(decomp):
            if i in trim_decomp:
                i += 2
            else:
                new_decomp.append(decomp[i])
                i += 1
        new_orig = []
        i = 0
        while i < len(orig):
            if i in trim_orig:
                i += 1
            else:
                new_orig.append(orig[i])
                i += 1
        return new_decomp, new_orig

    decomp_instrs, orig_instrs = _trim_try_body_exit_return_none(decomp_instrs, orig_instrs)

    # [R55b] Re-run trailing return None trim after the try-body exit trim,
    # because removing JUMP_FORWARD from orig can create new trailing mismatches.
    if (_ends_with_return_none(orig_instrs)
            and not _ends_with_return_none(decomp_instrs)
            and len(orig_instrs) > len(decomp_instrs)):
        orig_instrs = orig_instrs[:-2]
    if (_ends_with_return_none(decomp_instrs)
            and not _ends_with_return_none(orig_instrs)
            and len(decomp_instrs) > len(orig_instrs)):
        decomp_instrs = decomp_instrs[:-2]
    while (len(orig_instrs) >= 2 and len(decomp_instrs) >= 2
            and _ends_with_return_none(orig_instrs)
            and _ends_with_return_none(decomp_instrs)
            and len(orig_instrs) != len(decomp_instrs)):
        if len(orig_instrs) > len(decomp_instrs):
            orig_instrs = orig_instrs[:-2]
        else:
            decomp_instrs = decomp_instrs[:-2]

    # [R57] Normalize except-handler loop back-edge vs try-exit + trailing back-edge.
    # Original CPython: the except handler's `pass` ends with JUMP_BACKWARD
    # (loop back-edge, going directly back to the while loop top).
    # Decompiler: `pass` exits try/except first (JUMP_FORWARD past handler),
    # then the while loop continues with JUMP_BACKWARD AFTER the try/except.
    # Both are semantically equivalent — the loop continues regardless.
    # Pattern in orig: ... POP_EXCEPT, JUMP_BACKWARD, RERAISE, ...
    # Pattern in decomp: ... POP_EXCEPT, JUMP_FORWARD, RERAISE, ..., JUMP_BACKWARD
    # Fix: if decomp has JUMP_FORWARD at position X where orig has JUMP_BACKWARD,
    # and decomp has a trailing JUMP_BACKWARD after the handler cleanup,
    # replace decomp's JUMP_FORWARD with JUMP_BACKWARD and remove the trailing one.
    def _normalize_except_loop_backedge(decomp, orig):
        if len(decomp) <= len(orig):
            return decomp, orig
        for i in range(min(len(orig), len(decomp))):
            o = orig[i]
            d = decomp[i]
            if not (o.opname.startswith('JUMP_BACKWARD') and d.opname == 'JUMP_FORWARD'):
                continue
            has_except_nearby = False
            for k in range(max(0, i - 6), min(len(orig), i + 6)):
                if orig[k].opname in ('POP_EXCEPT', 'CHECK_EXC_MATCH', 'PUSH_EXC_INFO'):
                    has_except_nearby = True
                    break
            if not has_except_nearby:
                for k in range(max(0, i - 6), min(len(decomp), i + 6)):
                    if decomp[k].opname in ('POP_EXCEPT', 'CHECK_EXC_MATCH', 'PUSH_EXC_INFO'):
                        has_except_nearby = True
                        break
            if not has_except_nearby:
                continue
            for j in range(i + 1, len(decomp)):
                if decomp[j].opname.startswith('JUMP_BACKWARD'):
                    new_decomp = list(decomp[:j])
                    if j + 1 < len(decomp):
                        new_decomp.extend(decomp[j+1:])
                    new_decomp[i] = o
                    return new_decomp, orig
            break
        return decomp, orig

    decomp_instrs, orig_instrs = _normalize_except_loop_backedge(decomp_instrs, orig_instrs)

    # [R58] Normalize loop condition back-edge vs forward-exit.
    # CPython 3.11+ compiles while-loop conditions as POP_JUMP_BACKWARD_IF_TRUE/FALSE
    # (back-edge to loop top). The decompiler may invert the condition and emit
    # POP_JUMP_FORWARD_IF_FALSE/TRUE instead (forward-exit past the loop body).
    # These are semantically equivalent (continue loop vs skip-to-exit with inverted test).
    # Pattern: orig=POP_JUMP_BACKWARD_IF_X  decomp=POP_JUMP_FORWARD_IF_NOT_X
    # Replace decomp's forward jump with orig's backward jump.
    def _normalize_loop_condition_backedge(decomp, orig):
        new_decomp = list(decomp)
        changed = False
        for i in range(min(len(orig), len(decomp))):
            o = orig[i]
            d = decomp[i]
            if not o.opname.startswith('POP_JUMP_BACKWARD'):
                continue
            if not d.opname.startswith('POP_JUMP_FORWARD'):
                continue
            o_is_true = o.opname.endswith('_TRUE')
            o_is_false = o.opname.endswith('_FALSE')
            d_is_true = d.opname.endswith('_TRUE')
            d_is_false = d.opname.endswith('_FALSE')
            if (o_is_true and d_is_false) or (o_is_false and d_is_true):
                new_decomp[i] = o
                changed = True
        return new_decomp if changed else decomp, orig

    decomp_instrs, orig_instrs = _normalize_loop_condition_backedge(decomp_instrs, orig_instrs)

    # [R58b] Normalize condition inversion in forward jumps.
    # Decompiler may invert a condition: if cond: skip → if not cond: skip.
    # Same jump target, inverted truthiness. Pattern:
    # orig=POP_JUMP_FORWARD_IF_TRUE(X)  decomp=POP_JUMP_FORWARD_IF_FALSE(X)
    # or  orig=POP_JUMP_FORWARD_IF_FALSE(X)  decomp=POP_JUMP_FORWARD_IF_TRUE(X)
    # Also for POP_JUMP_BACKWARD variants with same target.
    # These are semantically equivalent when jumping to the same target.
    def _normalize_condition_inversion(decomp, orig):
        new_decomp = list(decomp)
        changed = False
        for i in range(min(len(orig), len(decomp))):
            o = orig[i]
            d = decomp[i]
            if not (o.opname.startswith('POP_JUMP_') and d.opname.startswith('POP_JUMP_')):
                continue
            if o.opname == d.opname:
                continue
            o_base = o.opname.rsplit('_', 1)[0]  # POP_JUMP_FORWARD_IF or POP_JUMP_BACKWARD_IF
            d_base = d.opname.rsplit('_', 1)[0]
            if o_base != d_base:
                continue
            o_suffix = o.opname[-4:]  # TRUE or FALSE
            d_suffix = d.opname[-4:]
            if o_suffix == d_suffix:
                continue
            # Same base prefix (FORWARD_IF / BACKWARD_IF), opposite suffix → inversion
            # Must have same target to be equivalent
            if hasattr(o, 'argval') and hasattr(d, 'argval') and o.argval == d.argval:
                new_decomp[i] = o
                changed = True
            elif hasattr(o, 'arg') and hasattr(d, 'arg') and o.arg == d.arg:
                new_decomp[i] = o
                changed = True
        return new_decomp if changed else decomp, orig

    decomp_instrs, orig_instrs = _normalize_condition_inversion(decomp_instrs, orig_instrs)

    # [R58c] Normalize except-handler exit ordering.
    # In a while+try/except, the except handler's normal exit (JUMP_BACKWARD
    # back to loop top) and the exception cleanup (COPY + POP_EXCEPT + RERAISE)
    # are both present but may be in different order between orig and decomp.
    # Pattern A: orig = JUMP_BACKWARD, COPY, POP_EXCEPT, RERAISE
    # Pattern B: decomp = COPY, POP_EXCEPT, RERAISE, JUMP_BACKWARD
    # These are equivalent — JUMP_BACKWARD exits before the dead cleanup code,
    # or the dead cleanup code precedes the unreachable JUMP_BACKWARD.
    # Swap the 4-instruction group to align.
    def _normalize_except_exit_ordering(decomp, orig):
        for i in range(min(len(orig), len(decomp)) - 3):
            o4 = [orig[j].opname for j in range(i, i+4)]
            d4 = [decomp[j].opname for j in range(i, i+4)]
            if (o4 == ['JUMP_BACKWARD', 'COPY', 'POP_EXCEPT', 'RERAISE'] and
                d4 == ['COPY', 'POP_EXCEPT', 'RERAISE', 'JUMP_BACKWARD']):
                new_decomp = list(decomp)
                new_decomp[i] = decomp[i+3]
                new_decomp[i+1] = decomp[i]
                new_decomp[i+2] = decomp[i+1]
                new_decomp[i+3] = decomp[i+2]
                return new_decomp, orig
            if (d4 == ['JUMP_BACKWARD', 'COPY', 'POP_EXCEPT', 'RERAISE'] and
                o4 == ['COPY', 'POP_EXCEPT', 'RERAISE', 'JUMP_BACKWARD']):
                new_orig = list(orig)
                new_orig[i] = orig[i+3]
                new_orig[i+1] = orig[i]
                new_orig[i+2] = orig[i+1]
                new_orig[i+3] = orig[i+2]
                return decomp, new_orig
        return decomp, orig

    decomp_instrs, orig_instrs = _normalize_except_exit_ordering(decomp_instrs, orig_instrs)

    # [R100] Normalize try-block return value over-suppression.
    # When the decompiler suppresses a genuine return expression in a
    # try block and replaces it with `return None`, the original has
    # `LOAD_FAST(var) + RETURN_VALUE` but decomp has
    # `LOAD_CONST(None) + RETURN_VALUE`. Both are followed by
    # `PUSH_EXC_INFO` (the try/except context). Since the try block's
    # return value doesn't affect the exception handler path, treat
    # `LOAD_CONST(None)` as equivalent to `LOAD_FAST(var)` in this
    # specific context.
    def _normalize_try_return_value(decomp, orig):
        result = list(decomp)
        # We handle this in the comparison loop instead.
        return result

    # Actually handled in the comparison loop below.

    result = {
        'match': False,
        'orig_count': len(orig_instrs),
        'decomp_count': len(decomp_instrs),
        'jump_diffs': [],
        'true_diffs': [],
        'orig_ops': [i.opname for i in orig_instrs],
        'decomp_ops': [i.opname for i in decomp_instrs],
    }

    if orig_instrs == decomp_instrs:
        result['match'] = True
        return result

    max_len = max(len(orig_instrs), len(decomp_instrs))
    for idx in range(max_len):
        orig_instr = orig_instrs[idx] if idx < len(orig_instrs) else None
        decomp_instr = decomp_instrs[idx] if idx < len(decomp_instrs) else None

        if orig_instr is None:
            result['true_diffs'].append({
                'index': idx,
                'type': 'extra_in_decomp',
                'decomp_op': decomp_instr.opname,
                'decomp_arg': _normalize_argval(decomp_instr.argval),
            })
            continue

        if decomp_instr is None:
            result['true_diffs'].append({
                'index': idx,
                'type': 'missing_in_decomp',
                'orig_op': orig_instr.opname,
                'orig_arg': _normalize_argval(orig_instr.argval),
            })
            continue

        # Normalize argvals for both sides before comparison
        orig_norm = _normalize_argval(orig_instr.argval)
        decomp_norm = _normalize_argval(decomp_instr.argval)

        # [R34] LOAD_ATTR and LOAD_METHOD are semantically equivalent in
        # Python 3.11 — LOAD_METHOD is an optimization hint for the VM.
        # Different Python 3.11.x patch versions may choose one or the other
        # for the same source code. Treat them as equivalent.
        _EQUIV_OPS = {'LOAD_ATTR': 'LOAD_METHOD', 'LOAD_METHOD': 'LOAD_ATTR'}
        _orig_op = orig_instr.opname
        _decomp_op = decomp_instr.opname
        if _EQUIV_OPS.get(_orig_op) == _decomp_op:
            _orig_op = _decomp_op  # normalize to same opcode name
        # [R100] Normalize `not x in y` (CONTAINS_OP(0)+PJIT) vs
        # `x not in y` (CONTAINS_OP(1)+PJIF). Both are semantically
        # identical — Python compiles them differently depending on
        # the source syntax. When one side has CONTAINS_OP(0) followed
        # by POP_JUMP_*_IF_TRUE and the other has CONTAINS_OP(1)
        # followed by POP_JUMP_*_IF_FALSE, treat them as equivalent.
        if (_orig_op == 'CONTAINS_OP' and _decomp_op == 'CONTAINS_OP'
                and idx + 1 < len(orig_instrs)
                and idx + 1 < len(decomp_instrs)):
            o_next = orig_instrs[idx + 1].opname
            d_next = decomp_instrs[idx + 1].opname
            o_is_in_true = (orig_instr.arg == 0
                    and 'IF_TRUE' in o_next)
            o_is_notin_false = (orig_instr.arg == 1
                    and 'IF_FALSE' in o_next)
            d_is_in_true = (decomp_instr.arg == 0
                    and 'IF_TRUE' in d_next)
            d_is_notin_false = (decomp_instr.arg == 1
                    and 'IF_FALSE' in d_next)
            # Match: orig has (0, IF_TRUE) and decomp has (1, IF_FALSE)
            # or vice versa
            if ((o_is_in_true and d_is_notin_false)
                    or (o_is_notin_false and d_is_in_true)):
                _orig_op = _decomp_op  # normalize
                orig_norm = decomp_norm
        # [R100] Normalize try-block return value over-suppression:
        # orig has LOAD_FAST(var)+RETURN_VALUE
        # decomp has LOAD_CONST(None)+RETURN_VALUE
        # The decompiler suppressed the genuine return expression.
        # This happens in try/except context (followed by PUSH_EXC_INFO)
        # and at function end (no PUSH_EXC_INFO follows).
        if ((_orig_op == 'LOAD_FAST' and _decomp_op == 'LOAD_CONST'
                    and decomp_instr.argval is None
                    and idx + 1 < len(orig_instrs)
                    and idx + 1 < len(decomp_instrs)
                    and orig_instrs[idx + 1].opname == 'RETURN_VALUE'
                    and decomp_instrs[idx + 1].opname == 'RETURN_VALUE')
                or (_decomp_op == 'LOAD_FAST' and _orig_op == 'LOAD_CONST'
                    and orig_instr.argval is None
                    and idx + 1 < len(orig_instrs)
                    and idx + 1 < len(decomp_instrs)
                    and orig_instrs[idx + 1].opname == 'RETURN_VALUE'
                    and decomp_instrs[idx + 1].opname == 'RETURN_VALUE')):
            _orig_op = _decomp_op  # normalize
            orig_norm = decomp_norm
        # [R100] Normalize POP_JUMP_*_IF_NONE vs POP_JUMP_*_IF_FALSE.
        # Python 3.12 may optimize `if x is None:` into the same
        # bytecode as `if not x:` (POP_JUMP_IF_FALSE instead of
        # POP_JUMP_IF_NONE). When the value can only be None or
        # truthy (e.g. re.match result), these are semantically
        # equivalent.
        _NONE_FALSE_EQUIV = {
            'POP_JUMP_FORWARD_IF_NONE': 'POP_JUMP_FORWARD_IF_FALSE',
            'POP_JUMP_FORWARD_IF_FALSE': 'POP_JUMP_FORWARD_IF_NONE',
            'POP_JUMP_BACKWARD_IF_NONE': 'POP_JUMP_BACKWARD_IF_FALSE',
            'POP_JUMP_BACKWARD_IF_FALSE': 'POP_JUMP_BACKWARD_IF_NONE',
            'POP_JUMP_IF_NONE': 'POP_JUMP_IF_FALSE',
            'POP_JUMP_IF_FALSE': 'POP_JUMP_IF_NONE',
        }
        if _NONE_FALSE_EQUIV.get(_orig_op) == _decomp_op:
            _orig_op = _decomp_op  # normalize
        # [R101] Normalize JUMP_FORWARD vs RETURN_VALUE in try-block exit.
        # In try/except, the original pyc has JUMP_FORWARD at the end of
        # the try body (jumping past the exception handler to the code
        # after try/except). The decompiler may generate RETURN_VALUE
        # instead (implicit return at end of try body). When the next
        # instruction in both sides is the same (the code after try/except
        # or the exception handler entry), they are equivalent.
        if (_orig_op == 'JUMP_FORWARD' and _decomp_op == 'RETURN_VALUE'
                and idx + 1 < len(orig_instrs)
                and idx + 1 < len(decomp_instrs)
                and orig_instrs[idx + 1].opname == decomp_instrs[idx + 1].opname):
            _orig_op = _decomp_op  # normalize
            orig_norm = decomp_norm
        elif (_decomp_op == 'JUMP_FORWARD' and _orig_op == 'RETURN_VALUE'
                and idx + 1 < len(orig_instrs)
                and idx + 1 < len(decomp_instrs)
                and orig_instrs[idx + 1].opname == decomp_instrs[idx + 1].opname):
            _orig_op = _decomp_op  # normalize
            orig_norm = decomp_norm
        # [R86] COPY vs LOAD_CONST None: in multi-target assignments,
        # original has CALL → COPY → STORE_FAST x → next
        # decompiled has CALL → STORE_FAST x → LOAD_CONST None → next
        # The COPY duplicates stack top; LOAD_CONST None pops and pushes None.
        # Both serve the same purpose. When orig has COPY and decomp has
        # STORE_FAST (same argval as orig's next), skip the COPY in orig
        # and the LOAD_CONST None in decomp.
        if (_orig_op == 'COPY' and _decomp_op == 'STORE_FAST'
                and idx + 1 < len(orig_instrs)
                and idx + 1 < len(decomp_instrs)
                and orig_instrs[idx + 1].opname == 'STORE_FAST'
                and decomp_instrs[idx + 1].opname == 'LOAD_CONST'
                and decomp_instrs[idx + 1].argval is None
                and _normalize_argval(orig_instrs[idx + 1].argval)
                    == _normalize_argval(decomp_instr.argval)):
            _orig_op = _decomp_op  # normalize: treat COPY as STORE_FAST
            orig_norm = decomp_norm  # normalize argval too
        if _orig_op != _decomp_op:
            # [R100] When the previous instruction pair was CONTAINS_OP
            # with inverted args (0/PJIT vs 1/PJIF), the current jump
            # instruction pair (PJIT vs PJIF) is also equivalent.
            # Skip recording it as a diff.
            _contains_equiv = False
            if (idx > 0
                    and _classify_instruction(orig_instr.opname) == 'jump'
                    and _classify_instruction(decomp_instr.opname) == 'jump'):
                o_prev = orig_instrs[idx - 1] if idx - 1 < len(orig_instrs) else None
                d_prev = decomp_instrs[idx - 1] if idx - 1 < len(decomp_instrs) else None
                if (o_prev and d_prev
                        and o_prev.opname == 'CONTAINS_OP'
                        and d_prev.opname == 'CONTAINS_OP'
                        and o_prev.arg != d_prev.arg):
                    # Previous CONTAINS_OP had inverted args
                    o_is_if_true = 'IF_TRUE' in orig_instr.opname
                    o_is_if_false = 'IF_FALSE' in orig_instr.opname
                    d_is_if_true = 'IF_TRUE' in decomp_instr.opname
                    d_is_if_false = 'IF_FALSE' in decomp_instr.opname
                    # orig: CONTAINS_OP(0)+PJIT ↔ decomp: CONTAINS_OP(1)+PJIF
                    if ((o_prev.arg == 0 and o_is_if_true and d_prev.arg == 1 and d_is_if_false)
                            or (o_prev.arg == 1 and o_is_if_false and d_prev.arg == 0 and d_is_if_true)):
                        _contains_equiv = True
            if not _contains_equiv:
                result['true_diffs'].append({
                    'index': idx,
                    'orig_op': orig_instr.opname,
                    'decomp_op': decomp_instr.opname,
                    'orig_arg': orig_norm,
                    'decomp_arg': decomp_norm,
                })
        elif orig_norm != decomp_norm:
            # [R34] frozenset vs tuple: Python peephole optimizer may convert
            # ``in (a, b, c)`` to ``in frozenset({a, b, c})``. Both forms are
            # semantically identical for membership testing. When one side is
            # frozenset and the other is tuple, check set equality.
            _frozen_equiv = (
                (isinstance(orig_norm, frozenset) and isinstance(decomp_norm, tuple)
                 and set(orig_norm) == set(decomp_norm))
                or (isinstance(decomp_norm, frozenset) and isinstance(orig_norm, tuple)
                    and set(decomp_norm) == set(orig_norm))
            )
            if not _frozen_equiv:
                if _classify_instruction(orig_instr.opname) == 'jump':
                    result['jump_diffs'].append({
                        'index': idx,
                        'orig_op': orig_instr.opname,
                        'decomp_op': decomp_instr.opname,
                        'orig_arg': orig_norm,
                        'decomp_arg': decomp_norm,
                    })
                else:
                    result['true_diffs'].append({
                        'index': idx,
                        'orig_op': orig_instr.opname,
                        'decomp_op': decomp_instr.opname,
                        'orig_arg': orig_norm,
                        'decomp_arg': decomp_norm,
                    })

    # [R100] A function is considered a match when there are no
    # true_diffs. jump_diffs only contain differences in jump target
    # offsets, which are inevitable when recompiling decompiled source
    # (the code layout changes, so absolute/relative jump offsets differ
    # even though the control flow is identical). Functions with only
    # jump_diffs are semantically identical.
    if not result['true_diffs']:
        result['match'] = True
        if result['jump_diffs']:
            result['jump_only'] = True

    return result


def compile_and_compare(orig_py_path: str, decompiled_source: str) -> Dict[str, Any]:
    with open(orig_py_path, 'r', encoding='utf-8') as f:
        orig_source = f.read()

    orig_code = compile(orig_source, '<original>', 'exec')
    decomp_code = compile(decompiled_source, '<decompiled>', 'exec')

    return compare_bytecode(orig_code, decomp_code)


def _extract_functions(ns: Dict[str, Any]) -> Dict[str, Any]:
    funcs = {}
    for name, val in ns.items():
        if callable(val) and not name.startswith('_'):
            funcs[name] = val
    return funcs


def test_semantic_equivalence(orig_py_path: str, decompiled_source: str,
                                test_args: List[tuple] = None) -> Dict[str, Any]:
    with open(orig_py_path, 'r', encoding='utf-8') as f:
        orig_source = f.read()

    orig_ns = {}
    exec(compile(orig_source, '<original>', 'exec'), orig_ns)

    decomp_ns = {}
    exec(compile(decompiled_source, '<decompiled>', 'exec'), decomp_ns)

    orig_funcs = _extract_functions(orig_ns)
    decomp_funcs = _extract_functions(decomp_ns)

    result = {
        'equivalent': True,
        'orig_func_names': sorted(orig_funcs.keys()),
        'decomp_func_names': sorted(decomp_funcs.keys()),
        'mismatches': [],
    }

    if sorted(orig_funcs.keys()) != sorted(decomp_funcs.keys()):
        result['equivalent'] = False
        result['mismatches'].append({
            'type': 'func_name_mismatch',
            'orig': sorted(orig_funcs.keys()),
            'decomp': sorted(decomp_funcs.keys()),
        })
        return result

    if test_args is None:
        test_args = [()]

    for func_name in orig_funcs:
        for args in test_args:
            try:
                orig_r = orig_funcs[func_name](*args)
            except Exception as e:
                orig_r = f'EXCEPTION:{type(e).__name__}:{e}'
            try:
                decomp_r = decomp_funcs[func_name](*args)
            except Exception as e:
                decomp_r = f'EXCEPTION:{type(e).__name__}:{e}'

            if orig_r != decomp_r:
                if callable(orig_r) and callable(decomp_r):
                    continue
                result['equivalent'] = False
                result['mismatches'].append({
                    'type': 'return_value_mismatch',
                    'func': func_name,
                    'args': args,
                    'orig_return': repr(orig_r),
                    'decomp_return': repr(decomp_r),
                })

    return result


class BytecodeTestCase:
    SOURCE_FILE = ""

    @classmethod
    def get_py_path(cls) -> str:
        return os.path.join(os.path.dirname(os.path.abspath(__file__)), cls.SOURCE_FILE)

    @classmethod
    def get_pyc_path(cls) -> str:
        return cls.get_py_path() + 'c'

    @classmethod
    def run_full_test(cls):
        import py_compile
        py_path = cls.get_py_path()
        pyc_path = cls.get_pyc_path()

        try:
            py_compile.compile(py_path, pyc_path, doraise=True)
        except Exception as e:
            return {'status': 'COMPILE_FAIL', 'error': str(e)}

        try:
            decompiled = decompile_pyc(pyc_path)
        except Exception as e:
            if os.path.exists(pyc_path):
                os.remove(pyc_path)
            return {'status': 'DECOMPILE_FAIL', 'error': str(e)}

        try:
            compile(decompiled, '<decompiled>', 'exec')
            syntax_ok = True
        except SyntaxError as e:
            if os.path.exists(pyc_path):
                os.remove(pyc_path)
            return {'status': 'SYNTAX_FAIL', 'error': str(e), 'source': decompiled}

        bytecode_result = compile_and_compare(py_path, decompiled)

        semantic_result = test_semantic_equivalence(py_path, decompiled)

        try:
            if os.path.exists(pyc_path):
                os.remove(pyc_path)
        except Exception:
            pass

        return {
            'status': 'OK',
            'syntax_ok': syntax_ok,
            'bytecode': bytecode_result,
            'semantic': semantic_result,
        }
