# -*- coding: utf-8 -*-
"""Round 40 G4': strict ruler over every product the landed core actually changed.

The 402-file mirror A/B said IMPROVED=3 / REGRESSION=0 / MOVED=33.  This gate re-derives
that verdict from the *shipped* bytes and from the products as committed, i.e. it closes any
gap between the harness's internal counting and `strict_compare` applied to real files:

  affected set = every all402 row whose (function -> verdict) differs between the two arms
  per row      = old committed *OK.py  vs  product regenerated by the landed core,
                 both recompiled and strict-compared against the same .pyc

  python -X utf8 g4prime40.py
"""
import importlib.util
import io
import json
import os
import subprocess
import sys

REPO = r'F:\Downloads\pythoncdc-main'
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, REPO)
sys.stdout.reconfigure(encoding='utf-8')

_s = importlib.util.spec_from_file_location('r10', os.path.join(REPO, '_r10_strict_check.py'))
r10 = importlib.util.module_from_spec(_s)
_s.loader.exec_module(r10)


def load(p):
    return [json.loads(x) for x in io.open(p, encoding='utf-8') if x.strip()]


A = {r['path']: r for r in load(os.path.join(HERE, 'h_all.jsonl'))}
B = {r['path']: r for r in load(os.path.join(HERE, 'c_all.jsonl'))}


def verdict(r):
    return {k: v for k, v in r.items() if k != 'arm'}


affected = [p for p in A if verdict(A[p]) != verdict(B[p])]
print('affected rows: %d of %d' % (len(affected), len(A)))

import pycdc  # noqa: E402  (repo == landed bytes)

PRODD = os.path.join(HERE, 'prod40')
if not os.path.isdir(PRODD):
    os.makedirs(PRODD)


def compile_map(src, tag):
    """_compile_map takes a path; keep every scratch artefact out of the repo."""
    fn = os.path.join(PRODD, tag + '.py')
    io.open(fn, 'w', encoding='utf-8', newline='\n').write(src)
    return r10._compile_map(fn)


nfix = nbroken = nsame = 0
for p in sorted(affected):
    stem = os.path.splitext(os.path.basename(p))[0]
    ok_rel = 'site-packages/' + os.path.relpath(p, os.path.join(REPO, 'site-packages'))[:-4] + 'OK.py'
    ok_rel = ok_rel.replace('\\', '/')
    try:
        old_src = subprocess.check_output(['git', 'show', 'HEAD:' + ok_rel], cwd=REPO).decode('utf-8')
    except Exception as e:
        print('  NO-HEAD-PRODUCT %s %s' % (ok_rel, repr(e)[:40]))
        continue
    new_src = pycdc.decompile_pyc(p)
    Os = r10._load_map(p)
    try:
        Bo = compile_map(old_src, stem + '_old')
        Bn = compile_map(new_src, stem + '_new')
    except Exception as e:
        print('  COMPILE-FAIL %s %s' % (p.split('site-packages/')[-1], repr(e)[:60]))
        nbroken += 1
        continue
    row = []
    for k in sorted(Os):
        do = r10.strict_compare(Os[k], Bo[k]) if k in Bo else ('missing', 'no product fn', True)
        dn = r10.strict_compare(Os[k], Bn[k]) if k in Bn else ('missing', 'no product fn', True)
        if do[2] and not dn[2]:
            row.append('FIX:' + k.split('.')[-1])
            nfix += 1
        elif dn[2] and not do[2]:
            row.append('BROKEN:' + k.split('.')[-1] + ':' + dn[1][:30])
            nbroken += 1
        elif do[2] and dn[2]:
            row.append('still:' + k.split('.')[-1] + ' %s|%s->%s' % (do[0][:4], do[1][-12:], dn[1][-12:]))
            nsame += 1
    if row:
        print('  %-64s %s' % (p.split('site-packages/')[-1], ' '.join(row)))
print('G4n: fixed=%d broken=%d still-defective(changed)=%d over %d affected files'
      % (nfix, nbroken, nsame, len(affected)))
json.dump({'affected': len(affected), 'fixed': nfix, 'broken': nbroken, 'still': nsame},
          io.open(os.path.join(HERE, 'g4prime40.json'), 'w', encoding='utf-8'), indent=1)
