"""Round-3 file-3 specimens (wizard_quant_api.pyc): B113 ternary-test and-chain inside
nested code objects (<genexpr>), B112 shared then-arm sink of mixed is-None or-chain.
Judge = scripts/pyc_verify.py only. Products regenerated by pycdc.py, never hand-edited.
"""
import json
import pathlib
import py_compile
import subprocess
import sys

ROOT = pathlib.Path(r'D:/admin/.qoder/worktrees/app/f557fd/pythoncdc-main')
D = ROOT / 'test_repros' / 'round3'

# --- B113: `A if A > 0 and A - B > 0 else 0` (two-conjunct and-test ternary) ---
G1 = r'''
def f(high, low, n1):
    return sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] - (low[-(i + 1)] - low[-i]) > 0 else 0 for i in range(1, n1 + 1)))
'''
G2 = r'''
def f(high, low, n1):
    dmp = sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, n1 + 1)))
    return dmp
'''
G3 = r'''
out = [high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, 9)]
'''
G4 = r'''
class C:
    def m(self, high, low, n1):
        return sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, n1 + 1)))
'''
G5 = r'''
def f(high, low, n1):
    return max((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, n1 + 1)), default=0)
'''
G6 = r'''
def f(high, low, n1):
    return sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, n1 + 1)))
'''
G7 = r'''
def f(high, low, n1):
    a = high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0
    return a
'''
G8 = r'''
def f(high, low, n1):
    for i in range(1, n1 + 1):
        try:
            acc = acc + (high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0)
        except TypeError:
            pass
    return acc
'''
G9 = r'''
fn = lambda high, low, n1: sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, n1 + 1)))
'''
G10 = r'''
def f(high, low, n1):
    return sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 or high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] else 0 for i in range(1, n1 + 1)))
'''
G11 = r'''
def f(high, low, n1):
    return sum((high[-i] - high[-(i + 1)] if high[-i] - high[-(i + 1)] > 0 and high[-i] - high[-(i + 1)] > low[-(i + 1)] - low[-i] and low[-(i + 1)] - low[-i] > 0 else 0 for i in range(1, n1 + 1)))
'''
# --- B112: shared then-arm sink of `x is None or y is None` inside elif chain ---
F1 = r'''
def f(filter_type, short_values, long_values):
    if filter_type == 'all_status':
        return 1
    elif filter_type == 'long_status':
        if short_values is None or long_values is None:
            return None
        return up_v(short_values[-1], long_values[-1])
    elif filter_type == 'short_status':
        if short_values is None or long_values is None:
            return None
        return down_v(short_values[-1], long_values[-1])
    return None
'''
F2 = r'''
def f(filter_type, short_values, long_values):
    if filter_type == 'short_status':
        if short_values is None or long_values is None:
            return None
        return down_v(short_values[-1], long_values[-1])
    return None
'''
F3 = r'''
def f(filter_type, short_values, long_values):
    if filter_type == 'short_status':
        if short_values is None and long_values is None:
            return None
        return down_v(short_values[-1], long_values[-1])
    return None
'''
F4 = r'''
def f(filter_type, short_values, long_values):
    if filter_type == 'short_status':
        if short_values is None or long_values is None:
            clean()
        return down_v(short_values[-1], long_values[-1])
    return None
'''
F5 = r'''
def f(a, x, y):
    if a:
        if x is None or y is None:
            return None
        return use(x, y)
    return None
'''

ARMS = {
    'r3_c01_genexpr_andtest_ternary_corpus': G1,
    'r3_c02_genexpr_andtest_ternary_assign': G2,
    'r3_c03_listcomp_andtest_ternary': G3,
    'r3_c04_method_host_genexpr_andtest': G4,
    'r3_c05_max_default_genexpr_andtest': G5,
    'r3_c06_genexpr_single_conjunct': G6,
    'r3_c07_plain_func_andtest_ternary': G7,
    'r3_c08_loop_try_host_andtest': G8,
    'r3_c09_lambda_host_andtest': G9,
    'r3_c10_genexpr_or_test_ternary': G10,
    'r3_c11_genexpr_three_conjuncts': G11,
    'r3_c12_elifchain_isnone_or_shared_sink': F1,
    'r3_c13_single_if_isnone_or_shared_sink': F2,
    'r3_c14_single_if_isnone_and_shared_sink': F3,
    'r3_c15_thenarm_stmt_not_return': F4,
    'r3_c16_minimal_if_a_isnone_or': F5,
}

names = sys.argv[1:] or sorted(ARMS)
for n in names:
    p = D / (n + '.py')
    p.write_text(ARMS[n].lstrip('\n'), encoding='utf-8')
    py_compile.compile(str(p), cfile=str(D / (n + '.pyc')), doraise=True, quiet=1)
    ok = D / (n + 'OK.py')
    if ok.exists():
        ok.unlink()
    r = subprocess.run([sys.executable, '-X', 'utf8', 'pycdc.py', '-o', str(ok),
                        str(D / (n + '.pyc'))], cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        print('DECOMPILE_FAIL', n, r.stderr[-200:])

f = D / 'r3_probe_index.json'
seen = [e['path'] for e in json.loads(f.read_text(encoding='utf-8'))] if f.exists() else []
merged = sorted(set(seen) | {f'test_repros/round3/{x}.pyc' for x in names})
f.write_text(json.dumps([{'path': x} for x in merged], indent=2), encoding='utf-8')
print('built', len(names), 'arms; index size', len(merged))
