# -*- coding: utf-8 -*-
"""AUTO-GENERATED by mk_big.py - R68-diag3 high-fidelity synthetic."""
from collections import OrderedDict
import datetime
Frequency = None
CAL_EXRIGHTS_COLUMNS = []
DIVIDEND_CALC_TYPE = []
get_kline_by_count_new = get_kline_by_count = get_kline_time_by_asset = 0
get_benchmark_datetime = get_dividends_info = 0
calculate_adjustment_factor_from_adj_value = get_adj_value = 0
is_one_of = lambda *a, **k: False
XDXRSecurity = type("XDXRSecurity", (), {"BIND": 0})
query_stock_period_data = query_stock_realtime_data = 0

def sink_big_sinkreturn(symbols, count, query_date, frequency=Frequency.DAILY.value, fields=None, fq=None, skip_suspended=False, include=False, execution_date=None, asset=None, dividends_all=None):
    _query_date = query_date // 100
    _min_datetime = _query_date // 10000 * 10000 + 930
    his_data_dict = OrderedDict()
    if include and _query_date > _min_datetime:
        count_min = 0
        query_time = str(query_date)
        if int(query_time[8:12]) <= 1130:
            minute_c = int((datetime.datetime.strptime(query_time, '%Y%m%d%H%M%S') - datetime.datetime.strptime(query_time[0:8] + '093000', '%Y%m%d%H%M%S')).seconds / 60)
            count_min = minute_c % int(frequency[:-1])
        elif int(query_time[8:12]) <= 1500:
            minute_c = int((datetime.datetime.strptime(query_time, '%Y%m%d%H%M%S') - datetime.datetime.strptime(query_time[0:8] + '130000', '%Y%m%d%H%M%S')).seconds / 60)
            count_min = minute_c % int(frequency[:-1])
        if count_min == 0:
            his_data_dict = get_kline_by_count_new(symbols, count, query_date, frequency, fields, fq, include, execution_date, asset, dividends_all)
            if len(his_data_dict) == 0:
                return his_data_dict
        else:
            add_fre_minute_time = datetime.datetime.strptime(query_time, '%Y%m%d%H%M%S') + datetime.timedelta(minutes=int(frequency[:-1]))
            fix_query_date = int(datetime.datetime.strftime(add_fre_minute_time, '%Y%m%d%H%M%S'))
            need_exrights = 0
            dividends_stock = []
            tmp_fields = CAL_EXRIGHTS_COLUMNS
            if fq is None or dividends_all is None or isinstance(fields, str) and fields not in tmp_fields or isinstance(fields, list) and len(set(fields).intersection(set(tmp_fields))) == 0:
                need_exrights = 0
            elif fq in DIVIDEND_CALC_TYPE:
                dividends_stock = dividends_all.keys()
                need_exrights = 1
            start_000300, end_000300 = get_benchmark_datetime(count, fix_query_date, frequency, fields, include, execution_date)
            if not start_000300 is not None or end_000300 is None:
                return OrderedDict()
            else:
                for symbol in symbols:
                    asset_one = asset[symbol]
                    stock = symbol.replace('SS', 'XSHG').replace('SZ', 'XSHE')
                    need_exrights_one = 0
                    dividends = None
                    if need_exrights == 1:
                        if stock not in dividends_stock:
                            need_exrights_one = 0
                            dividends = None
                        else:
                            need_exrights_one = need_exrights
                            dividends = dividends_all[stock]
                    his_data_fix = get_kline_by_count(symbol, count, fix_query_date, frequency, None, fq, include, execution_date, asset_one, need_exrights_one, dividends, start_000300, end_000300)
                    if len(his_data_fix) == 0:
                        his_data_dict[symbol] = his_data_fix[fields]
                        continue
                    if len(his_data_fix) < count:
                        if his_data_fix['datetime'][-1] < query_date:
                            his_data_dict[symbol] = his_data_fix[fields]
                            continue
                        fix_data = get_kline_by_count(symbol, count_min, query_date, '1m', None, fq, include, execution_date, asset_one, need_exrights_one, dividends)
                    else:
                        fix_data = get_kline_by_count(symbol, count_min, query_date, '1m', None, fq, include, execution_date, asset_one, need_exrights_one, dividends)
                    if len(fix_data) == 0:
                        his_data_dict[symbol] = his_data_fix[fields]
                        continue
                    his_data_fix['open'][-1] = fix_data['open'][0].copy()
                    his_data_fix['high'][-1] = fix_data['high'].max().copy()
                    his_data_fix['low'][-1] = fix_data['low'].min().copy()
                    his_data_fix['close'][-1] = fix_data['close'][-1].copy()
                    his_data_fix['volume'][-1] = fix_data['volume'].sum().copy()
                    his_data_fix['money'][-1] = fix_data['money'].sum().copy()
                    his_data_fix['price'][-1] = fix_data['price'][-1].copy()
                    his_data_dict[symbol] = his_data_fix[fields]
                    continue
    else:
        his_data_dict = get_kline_by_count_new(symbols, count, query_date, frequency, fields, fq, include, execution_date, asset, dividends_all)
    return his_data_dict
